version: '3.8'

services:
  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.3.0
    container_name: airflow_git_sync
    user: "1000:0"
    restart: always
    env_file:
      - ../05_git_based_dag_retrieval/.env.git-sync
    environment:
      GITSYNC_ROOT: /dags/.git-sync-root
      GITSYNC_LINK: /dags/repo
      GITSYNC_ONE_TIME: "false"
      GITSYNC_SSH_KNOWN_HOSTS: "false"
    volumes:
      - ../01_install/dags:/dags
    command: ["--verbose=3"]
    networks:
      - airflow-net

networks:
  airflow-net:
    external: true
    name: airflow-net
